### ISSUE TITLE
Hide menu bar

### ISSUE THREAD

**Issue by lolrepeatlol** [Alex313031/apple-music-desktop#2]
Would it be possible to get a feature to hide the menu bar? 

To access menu bar functionality, perhaps you could press the Alt key to temporarily show those options. I believe that is the default behavior in Electron apps, but please correct me if I'm wrong.

**Comment by Alex313031** [comment]
@lolrepeatlol Here you go! > https://github.com/Alex313031/apple-music-desktop/releases/tag/2.1.1

**Comment by lolrepeatlol** [comment]
Thanks so much!
